Remove a lot of code duplication.
Signed-off-by: Jason Hellenthal <jhellenthal@DataIX.net>

diff --git a/platform-upgrade b/platform-upgrade
--- a/platform-upgrade
+++ b/platform-upgrade
@@ -8,6 +8,15 @@ platform_dir="platform-$version"
 platform_url="$host$latest_path/$platform_file"
 md5sums_url="$host$latest_path/md5sums.txt"
 
+_check_return(){
+	if [ $? -gt 0  ]; then
+		echo " failed"
+		exit -1
+	else
+	        echo " OK"
+	fi
+}
+
 force="false"
 while getopts :f option; do
 	case "$option" in
@@ -22,7 +31,7 @@ while getopts :f option; do
 done
 shift $((OPTIND-1))
 
-IFS=_ read brand kernel << $(uname -v)
+IFS=_ read brand kernel < <(uname -v)
 if [ "$kernel" == "$version" ]; then
 	echo "Already on latest version ($kernel)."
 	$force ||exit -1
@@ -31,46 +40,30 @@ fi
 tmp="$(mktemp -d)"
 cd "$tmp" ||exit -1
 
-echo -n "Downloading latest platform ($platform_file)..."
-if [ ! $(curl -sk -o "$platform_file" "$platform_url") ]; then
-	echo " failed"
-	exit -1
-else
-	echo " OK"
-fi
+echo "Downloading latest platform ($platform_file)..."
+curl -sk -o "$platform_file" "$platform_url"
+_check_return
 
-echo -n "Verifying checksum..."
+echo "Verifying checksum..."
 curl -sk "$md5sums_url" \
 	|grep "$platform_file" \
 	|awk '{print $1}' > expected.md5
 openssl md5 "$platform_file" |awk '{print $2}' > actual.md5
-if [ ! "$(cmp -s actual.md5 expected.md5)" ]; then
-	echo " failed"
-	exit -1
-else
-	echo " OK"
-fi
+cmp -s actual.md5 expected.md5
+_check_return
 
-echo -n "Extracting latest platform..."
-if [ ! $(gtar zxf "$platform_file") ]; then
-	echo " failed"
-	exit -1
-else
-	echo " OK"
-fi
+echo "Extracting latest platform..."
+gtar zxf "$platform_file"
+_check_return
 
-echo -n "Marking release version..."
-if [ ! "$(echo $version > $platform_dir/VERSION)" ]; then
-	echo " failed"
-	exit -1
-else
-	echo " OK"
-fi
+echo "Marking release version..."
+echo $version >"$platform_dir/VERSION"
+_check_return
 
-echo -n "Checking current boot device..."
+echo "Checking current boot device..."
 if [ -z "$1" ]; then
-	removables="($(disklist -r))"
-	echo -n " detected ${removables[@]}"
+	removables="$(disklist -r)"
+	echo " detected ${removables[@]}"
 	if [ "${#removables[@]}" -gt 1 ]; then
 		echo
 		echo "Error: more than one removable device detected."
@@ -80,70 +73,50 @@ if [ -z "$1" ]; then
 	usb="/dev/dsk/${removables[0]}p1"
 else
 	usb="$1"
-	echo -n " using $usb"
+	echo " using $usb"
 fi
 
 umount "$usb" 2>/dev/null
 mkdir usb
-if [ ! $(mount -F pcfs -o foldcase "$usb" "$tmp/usb") ]; then
+mount -F pcfs -o foldcase "$usb" "$tmp/usb"
+if [ $? -gt 0 ]; then
 	echo ", mount failed"
 	exit -1
 else
-	echo -n ", mounted"
+	echo ", mounted"
 fi
 
-if [ ! -d usb/platform ] ; then
+if [ ! -d usb/platform ]; then
 	echo ", missing platform dir"
 	exit -1
 else
 	echo ", OK"
 fi
 
-echo -n "Updating platform on boot device..."
-if [ ! $(rsync -a "$platform_dir/" usb/platform.new/) ]; then
-	echo " failed"
-	exit -1
-else
-	echo " OK"
-fi
+echo "Updating platform on boot device..."
+rsync -a "$platform_dir/" usb/platform.new/
+_check_return
 
-echo -n "Remounting boot device..."
+echo "Remounting boot device..."
 umount "$usb" 2>/dev/null
-if [ ! $(mount -F pcfs -o foldcase "$usb" "$tmp/usb") ]; then
-	echo " failed"
-	exit -1
-else
-	echo " OK"
-fi
+mount -F pcfs -o foldcase "$usb" "$tmp/usb"
 
-echo -n "Verifying kernel checksum on boot device..."
+echo "Verifying kernel checksum on boot device..."
 openssl dgst -sha1 "$platform_dir"/i86pc/kernel/amd64/unix |cut -d ' ' -f 2 > kernel.expected
 openssl dgst -sha1 usb/platform.new/i86pc/kernel/amd64/unix |cut -d ' ' -f 2 > kernel.actual
-if [ ! "$(cmp -s kernel.actual kernel.expected)" ]; then
-	echo " failed"
-	exit -1
-else
-	echo " OK"
-fi
+cmp -s kernel.actual kernel.expected
+_check_return
 
-echo -n "Verifying boot_archive checksum on boot device..."
+echo "Verifying boot_archive checksum on boot device..."
 openssl dgst -sha1 usb/platform.new/i86pc/amd64/boot_archive |cut -d ' ' -f 2 > boot_archive.actual
-if [ ! "$(cmp -s boot_archive.actual usb/platform.new/i86pc/amd64/boot_archive.hash)" ]; then
-	echo " failed"
-	exit -1
-else
-	echo " OK"
-fi
+cmp -s boot_archive.actual usb/platform.new/i86pc/amd64/boot_archive.hash
+_check_return
 
-echo -n "Activating new platform on $usb..."
+echo "Activating new platform on $usb..."
 rm -rf usb/old
 mkdir usb/old
-if [ ! "$(mv usb/platform usb/old && mv usb/platform.new usb/platform)" ]; then
-	echo " failed"
-	exit -1
-else
-	echo " OK"
-fi
+mv usb/platform usb/old && mv usb/platform.new usb/platform
+_check_return
 
 echo "
 
